server:
  port: 8001
spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://ali.renqzh.com:3306/takeout?&serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: 957809494
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

eureka:
  client:
    #表示是否将自己注册进EurekaServer 默认为 true
    register-with-eureka: true
    #是否从eurekaServer抓取已有的注册信息，默认为true.单点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #服务注册中心的集群
      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka/
  instance:
    instance-id: payment8001
    #访问路径可以显示ip
    prefer-ip-address: true

mybatis:
  mapperlocation: classpath:mapper/*.xml

logging:
  level:
    com:
      jinan:
        springcloud: debug




