server:
  port: 8001

spring:
  application:
    name: cloud-provider-hystrix-payment

eureka:
  client:
    register-with-erueka: true
    fetch-register: true
#单机版
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#服务端不用开启hystrix
#feign:
#  hystrix:
#    enable: true



